## Settings
title: HQ-BLOG
owner: "heqiao2010"
url: "https://heqiao2010.github.io"
baseurl: "/HQ-BLOG"
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "he_qiao_2010@yeah.net"
github: "heqiao2010/HQ-BLOG"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "Designed by DeerRIDER, All Rights Reserved"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"
